const express = require('express');
const router = express.Router();
const StudentQR = require('../models/StudentQR');
const Student = require('../models/Student');
const Attendance = require('../models/Attendance');

// @route   POST /api/attendance/qr-mark
// @desc    Mark attendance via QR Scan
// @access  Admin (Scanner)
router.post('/qr-mark', async (req, res) => {
    try {
        const { studentId, token } = req.body;

        // 1. Validate inputs
        if (!studentId || !token) {
            return res.status(400).json({ success: false, message: 'Invalid QR Data' });
        }

        // 2. Find Student and QR Record
        // Input studentId is likely the MongoID string from the QR JSON
        // But might be Supabase UUID if generated by older code. Handle both.
        let student = null;
        if (studentId.match(/^[0-9a-fA-F]{24}$/)) {
            student = await Student.findById(studentId);
        } else {
             // Try valid supabase ID lookup
             student = await Student.findOne({ supabaseId: studentId });
        }

        if (!student) {
            return res.status(404).json({ success: false, message: 'Student lookup failed' });
        }

        const studentQR = await StudentQR.findOne({ studentId: student._id });
        if (!studentQR) {
            return res.status(400).json({ success: false, message: 'QR Record not found' });
        }

        // 3. Validate Token
        if (studentQR.qrToken !== token) {
            return res.status(401).json({ success: false, message: 'Invalid or Expired QR Token' });
        }

        // 4. Check Duplicate Attendance (One per day)
        const startOfDay = new Date();
        startOfDay.setHours(0, 0, 0, 0);
        
        const endOfDay = new Date();
        endOfDay.setHours(23, 59, 59, 999);

        const existingAttendance = await Attendance.findOne({
            studentId: student._id,
            date: { $gte: startOfDay, $lte: endOfDay }
        });

        if (existingAttendance) {
            return res.json({ 
                success: false, 
                message: 'Attendance Already Marked Today',
                student: { name: student.name, email: student.email }
            });
        }

        // 5. Mark Attendance
        // Create new attendance record
        // We use current server time for `date`
        const newAttendance = await Attendance.create({
            studentId: student._id,
            status: 'present',
            method: 'qr',
            markedBy: 'qr-scanner',
            date: new Date()
        });

        res.json({
            success: true,
            message: 'Attendance Marked Successfully',
            student: {
                name: student.name,
                email: student.email,
                scanTime: newAttendance.date
            }
        });

    } catch (err) {
        console.error('Attendance Mark Error:', err);
        res.status(500).json({ success: false, message: 'Server Error' });
    }
});

// @route   GET /api/attendance/today
// @desc    Get all students present today (for admin monitor)
// @access  Admin
router.get('/today', async (req, res) => {
    try {
        const startOfDay = new Date();
        startOfDay.setHours(0, 0, 0, 0);
        
        const endOfDay = new Date();
        endOfDay.setHours(23, 59, 59, 999);

        const records = await Attendance.find({
            date: { $gte: startOfDay, $lte: endOfDay }
        }).populate('studentId', 'name email')
          .sort({ date: -1 });

        res.json(records);

    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Server Error' });
    }
});

// @route   GET /api/attendance/history
// @desc    Get attendance history with filters
// @access  Admin
router.get('/history', async (req, res) => {
    try {
        const { startDate, endDate, studentId } = req.query;
        
        let query = {};

        // Date Filter
        if (startDate || endDate) {
            query.date = {};
            if (startDate) {
                const start = new Date(startDate);
                start.setHours(0, 0, 0, 0);
                query.date.$gte = start;
            }
            if (endDate) {
                const end = new Date(endDate);
                end.setHours(23, 59, 59, 999);
                query.date.$lte = end;
            }
        }

        // Student Filter (Optional)
        if (studentId) {
            // Check if it's a valid Mongo ObjectId
            if (studentId.match(/^[0-9a-fA-F]{24}$/)) {
                query.studentId = studentId;
            } else {
                // Assume Supabase UUID, look up student _id
                const student = await Student.findOne({ supabaseId: studentId });
                if (student) {
                    query.studentId = student._id;
                } else {
                    // If student not found by UUID, return empty result instantly
                    return res.json([]);
                }
            }
        }

        const records = await Attendance.find(query)
            .populate('studentId', 'name email')
            .sort({ date: -1 });

        res.json(records);

    } catch (err) {
        console.error('History Error:', err);
        res.status(500).json({ message: 'Server Error' });
    }
});

module.exports = router;
